---
title: "SalidasInformeFinal-junio 2021"
output: pdf_document
---

```{r llama codigos, warning=F, include=T, message=F, echo=FALSE}
library(knitr) # para generar reporte Rmarkdown
library(stringr)
library(reshape) 
library(dplyr) 
library(ggplot2)
library(ggthemes) # para ggplot
library(patchwork) # para unir gráficos de ggplot
library(strucchange) # libreria utilizada para análisis de quiebres

dir.Fig     <-"Figuras/" # carpeta de las figuras utilizadas y generadas en este estudio
fig         <-c("pdf") # formato de figuras generadas por este código
dir.0       <-getwd() # directorio de trabajo 
dir.1       <-paste(dir.0,"/codigos_admb",sep="") # carpeta de códigos ADMB 
dir.2       <-paste(dir.0,"/Retrospectivobase",sep="") # carpeta de códigos ADMB 
dir.3       <-paste(dir.0,"/Retrospectivoalternativo",sep="") # carpeta de códigos ADMB 
dir.4       <-paste(dir.0,"/Verosimilitudalternativo",sep="") # carpeta de códigos ADMB 
dir.5       <-paste(dir.0,"/Verosimilitudbase",sep="") # carpeta de códigos ADMB 

dir.fun     <-paste(dir.0,"/funciones/",sep="") # carpeta de funciones utilizadas en este informe
source(paste(dir.fun,"functions.R",sep="")) # funciones para leer .dat y .rep
source(paste(dir.fun,"Fn_PBRs.R",sep="")) # funciones para leer .dat y .rep
```

```{r CORRE MODELO BASE SEPTIEMBRE, eval=FALSE, echo=FALSE, warning=FALSE,include=F}
#Primer paso correr códigos 
setwd(dir.1)
#Asesoría Septiembre 2021
system("~/admb-12.2/admb MTT0920")
system("./MTT0920")
```

```{r CORRE MODELO BASE JUNIO, eval=FALSE, echo=FALSE, warning=FALSE,include=F}
#Primer paso correr códigos 
setwd(dir.1)
system("~/admb-12.2/admb MTT0621")
system("./MTT0621")
```

```{r datos_rep_std, warning=F, include=T, message=F, echo=FALSE}
setwd(dir.1)
#Asesoría septiembre 2020 MODELO BASE 
data.0   <- lisread(paste(dir.1,"MTT0920.dat", sep='/'));
names(data.0)<-str_trim(names(data.0), side="right")
rep0     <- reptoRlist("MTT0920.rep")                                               
std0     <- read.table("MTT0920.std",header=T,sep="",na="NA",fill=T) 

#Asesoría junio 2021 MODELO BASE  
data.1   <- lisread(paste(dir.1,"MTT0621.dat", sep='/'));
names(data.1)<-str_trim(names(data.1), side="right")
rep1     <- reptoRlist("MTT0621.rep")                                               
std1     <- read.table("MTT0621.std",header=T,sep="",na="NA",fill=T) 

```

```{r CARPETA RETROSPECTIVOBaseSept, eval=FALSE, echo=FALSE, warning=FALSE,include=F}
source(paste(getwd(),"/funciones/Fn_Retrospectivo.R",sep="")) 
Retrospectivobase("MTT0920",dir.0,dir.1,"/RetrospectivobaseSept",system="mac") 
```

```{r CARPETA RETROSPECTIVOBaseJun, eval=FALSE, echo=FALSE, warning=FALSE,include=F}
source(paste(getwd(),"/funciones/Fn_Retrospectivo.R",sep="")) 
Retrospectivobase("MTT0621",dir.0,dir.1,"/RetrospectivobaseJun",system="mac") 
```

```{r CARPETA VEROSIMILITUDBaseSept, eval=FALSE, echo=FALSE, warning=FALSE,include=F}
source(paste(getwd(),"/funciones/Fn_Verosimilitud.R",sep="")) 
Verosimilitudbase("MTT0920",dir.0,dir.1,"/VerosimilitudbaseSept",system="mac") 
```

```{r CARPETA VEROSIMILITUDBaseJun, eval=FALSE, echo=FALSE, warning=FALSE,include=F}
source(paste(getwd(),"/funciones/Fn_Verosimilitud.R",sep="")) 
Verosimilitudbase("MTT0621",dir.0,dir.1,"/VerosimilitudbaseJun",system="mac") 
```

```{r CARPETA ProyeccionAlternativo_Asesoriasept2019, eval=FALSE, echo=FALSE, warning=FALSE,include=F}
source(paste(getwd(),"/funciones/Fn_CBA.R",sep="")) 

admb<-"MAT0919"
Carpeta<-"/cba_septiembre2019_alternativo"
system="mac"
l_escRec=166

CBA(admb,dir.0,dir.1,Carpeta,system,l_escRec)
  
```

```{r CARPETA ProyeccionAlternativo_Asesoriasept2020, eval=FALSE, echo=FALSE, warning=FALSE,include=F}
source(paste(getwd(),"/funciones/Fn_CBA.R",sep="")) 

admb<-"MAT0920"
Carpeta<-"/cba_septiembre2020_alternativo"
system="mac"
l_escRec=169

CBA(admb,dir.0,dir.1,Carpeta,system,l_escRec)
  
```

```{r CARPETA ProyeccionBase_Asesoriasept2019, eval=FALSE, echo=FALSE, warning=FALSE,include=F}
source(paste(getwd(),"/funciones/Fn_CBA.R",sep="")) 

admb<-"MTT0819"
Carpeta<-"/cba_septiembre2019_base"
system="mac"
l_escRec=188

CBA(admb,dir.0,dir.1,Carpeta,system,l_escRec)
  
```

```{r CARPETA ProyeccionBase_Asesoriasept2020, eval=FALSE, echo=FALSE, warning=FALSE,include=F}
source(paste(getwd(),"/funciones/Fn_CBA.R",sep="")) 

admb<-"MTT0920"
Carpeta<-"/cba_septiembre2020_base"
system="mac"
l_escRec=186

CBA(admb,dir.0,dir.1,Carpeta,system,l_escRec)
  
```

```{r correr codigos asesorías previas, eval=FALSE, echo=FALSE, warning=FALSE}
#Primer paso correr códigos 
setwd(dir.1)
#modelo base
#system("~/admb-12.2/admb MTT0520")
#system("./MTT0520")

#system("./MTT0819")
##system("~/admb-12.2/admb MTT0819")

#modelo alternativo
#system("~/admb-12.2/admb MAT0420")
#system("./MAT0420")

#alternativo septiembre 2019
#system("~/admb-12.2/admb MAT0919")
#system("./MAT0919")

#alternativo julio 2019
#system("~/admb-12.2/admb MAT0619")
#system("./MAT0619")

```

```{r datos_rep_, warning=F, include=T, message=F, echo=FALSE}
setwd(dir.1)
#modelo base junio 2020
data0   <- lisread(paste(dir.1,"MTT0520.dat", sep='/'));names(data0)<-str_trim(names(data0), side="right")
rep.0     <- reptoRlist("MTT0520.rep")                                          
std.0     <- read.table("MTT0520.std",header=T,sep="",na="NA",fill=T) 

#modelo base septiembre 2019
data0a   <- lisread(paste(dir.1,"MTT0819.dat", sep='/'));names(data0a)<-str_trim(names(data0a), side="right")
rep.0a     <- reptoRlist("MTT0819.rep")                                        
std.0a     <- read.table("MTT0819.std",header=T,sep="",na="NA",fill=T) 

#modelo alternativo junio 2020
data1   <- lisread(paste(dir.1,"MAT0420.dat", sep='/'));names(data1)<-str_trim(names(data1), side="right")
rep.1     <- reptoRlist("MAT0420.rep")                                          
std.1     <- read.table("MAT0420.std",header=T,sep="",na="NA",fill=T) 

#modelo alternativo septiembre 2019
data2   <- lisread(paste(dir.1,"MAT0919.dat", sep='/'));names(data2)<-str_trim(names(data2), side="right")
rep.2     <- reptoRlist("MAT0919.rep")                                          
std.2     <- read.table("MAT0919.std",header=T,sep="",na="NA",fill=T) 

#modelo alternativo junio 2019
data3   <- lisread(paste(dir.1,"MAT0619.dat", sep='/'));names(data3)<-str_trim(names(data3), side="right")
rep.3     <- reptoRlist("MAT0619.rep")                                          
std.3     <- read.table("MAT0619.std",header=T,sep="",na="NA",fill=T) 

```

## Antecedentes


```{r Fig2,warning=F, include=T, message=F,eval=T, echo=FALSE,fig.height=3.5,fig.width=5,fig.align="center",fig.path="Figuras/",dev=fig}
year<-seq(2006,2020,1)
desemb<-c(39146,50506,45078,49225,20123,16429,19763,21888,22951,23643,18495,14134,8366,12565,14213)
cuota<-c(40522,50872,41904,58481,30966,17693,14500,21670,18276,23848,18380,20000,18897,11137,15471)


par(mfcol=c(1,1),mar=c(4,4,1,1))
plot(year,desemb,type="h",lwd=15,ylab="Desembarques (t.)",xlab="Año",ylim=c(0,60000),xaxp=c(2000,2021,21),col="cadetblue4",cex.lab=0.8,cex.axis=0.8)
lines(year,cuota,type="l",lwd=2,col=1)
legend(2011,60000,c("Datos oficiales","CBA"),lwd=c(10,2),col=c("cadetblue4",1),bty="n",cex=0.8)
```


```{r Fig3,eval=T,warning=F, include=T, message=F, echo=FALSE,fig.height=7.5,fig.width=6,fig.align="center",fig.path="Figuras/",dev=fig}

datafrec<-read.table(paste(getwd(),"/Tallasmensuales.txt",sep=""),header = FALSE, sep = "")

tallas     <-seq(5.5,20,0.5)                                            
ntallas    <-length(tallas)    
etf_obs <- data.frame(datafrec[,3:32])
yearf   <- datafrec[,1]
nyearf  <-length(yearf)  
month <- datafrec[,2]
nmonth <-length(month)

obs  <- as.data.frame(etf_obs) %>% mutate(year=yearf) %>% mutate(mes=month) %>% melt(id.vars=c('year','mes'))%>%
          mutate(talla = rep(tallas, each=nyearf)) 


fig0 <-   ggplot(filter(obs,year==2017)) + 
          geom_bar(aes(x = talla, y = value), stat="identity", fill='gray66', color = 'gray28') + 
          facet_grid(mes~year) + 
          labs(x = '', y = 'Proporción de tallas de la captura')  + 
          theme(panel.background = element_rect(fill ="gray99"),axis.text.y = element_text(hjust = 1, size=6)) + 
          theme(panel.grid=element_line(color=NA)) +
          scale_x_continuous(breaks = seq(from = 2, to = 20, by = 2))+
          scale_y_continuous(breaks = seq(from = 0, to = 0.3, by = 0.1))

fig1 <-   ggplot(filter(obs,year==2018)) + 
          geom_bar(aes(x = talla, y = value), stat="identity", fill='gray66', color = 'gray28') + 
          facet_grid(mes~year) + 
          labs(x = 'Tallas', y = 'Proporción de tallas de la captura')  + 
          theme(panel.background = element_rect(fill ="gray99"),axis.text.y = element_text(hjust = 1, size=6)) + 
          theme(panel.grid=element_line(color=NA)) + 
          scale_x_continuous(breaks = seq(from = 2, to = 20, by = 2)) +
          scale_y_continuous(breaks = seq(from = 0, to = 0.3, by = 0.1)) 
          
fig2 <-   ggplot(filter(obs,year==2019)) + 
          geom_bar(aes(x = talla, y = value), stat="identity", fill='gray66', color = 'gray28') + 
          facet_grid(mes~year) + 
          labs(x = '', y = '')  + 
          theme(panel.background = element_rect(fill ="gray99"),axis.text.y = element_text(hjust = 1, size=6)) + 
          theme(panel.grid=element_line(color=NA)) +
          scale_x_continuous(breaks = seq(from = 2, to = 20, by = 2))+
          scale_y_continuous(breaks = seq(from = 0, to = 0.3, by = 0.1))  
          
fig3 <-   ggplot(filter(obs,year==2020)) + 
          geom_bar(aes(x = talla, y = value), stat="identity", fill='gray66', color = 'gray28') + 
          facet_grid(mes~year) + 
          labs(x = 'Tallas', y = '')  + 
          theme(panel.background = element_rect(fill ="gray99"),axis.text.y = element_text(hjust = 1, size=6)) + 
          theme(panel.grid=element_line(color=NA)) +
          scale_x_continuous(breaks = seq(from = 2, to = 20, by = 2))+
          scale_y_continuous(breaks = seq(from = 0, to = 0.3, by = 0.1))

fig0+fig2+fig1+fig3

```

## Metodología 


```{r Fig7,warning=F, include=T, message=F, echo=FALSE,fig.height=3,fig.width=6,fig.align="center",fig.path="Figuras/",dev=c('pdf')}

dirb<-paste(dir.0,"/cba_septiembre2020_base",sep="")
setwd(dirb)
reps1b     <- reptoRlist("MTT0920s1.rep")  
reps2b     <- reptoRlist("MTT0920s2.rep") 
reps3b     <- reptoRlist("MTT0920s3.rep") 



par(mfcol=c(1,1),mar=c(2,4,1,1)+0.5)

# modelo base
plot(reps1b$Years,reps1b$Reclutamiento,type="l",ylab="Reclutamientos",xlab="",main="Modelo base (Asesoría Septiembre 2020)",cex.axis=0.6,cex.main=0.7,cex.lab=0.7)
abline(h=c(exp(8.6053e+000),reps2b$Reclutamiento[11],reps3b$Reclutamiento[17]),col=c(1,2,3))
text(2010,c(exp(8.6053e+000),reps2b$Reclutamiento[11],reps3b$Reclutamiento[17])+1000,round(c(exp(8.6053e+000),reps2b$Reclutamiento[11],reps3b$Reclutamiento[17]),0),cex=0.7)


```


## Salidas de ajustes 


```{r Fig19,warning=F, include=T, message=F, echo=FALSE,fig.height=6.5,fig.width=5.5,fig.align="center",fig.path="Figuras/",dev=fig}

library(patchwork)

yrs   <- rep1$Years
nyrs  <- length(yrs)
lasty <- yrs[nyrs]
cvCB   <-data.1$Ind[,7]
cvcpue <-data.1$Ind[,5]
cvdes  <-data.1$Ind[,3]

ind_obs  <- cbind(c(rep0$Bcru_obs,NA),c(rep0$CPUE_obs,NA), c(rep0$Desemb_obs,NA)); ind_obs[ind_obs==0] <- NA
colnames(ind_obs) <- c('Biomasa_Crucero', 'CPUE', 'Desembarques') 
ind      <- data.frame(ind_obs) %>% mutate(Asesoría='observado') %>% mutate (yrs= yrs) %>% melt(id.var=c('yrs', 'Asesoría'))  
        
ind_jun <- cbind(c(rep1$Bcru_pred), c(rep1$CPUE_pred), c(rep1$Desemb_pred)) ; 
colnames(ind_jun) <- c('Biomasa_Crucero', 'CPUE', 'Desembarques') 
junio     <- data.frame(ind_jun) %>% mutate (Asesoría='junio_2020') %>% mutate (yrs= yrs)  %>% melt(id.var=c('yrs', 'Asesoría'))

ind_sept <- cbind(c(rep0$Bcru_pred,NA), c(rep0$CPUE_pred,NA), c(rep0$Desemb_pred,NA)) ; 
colnames(ind_sept) <- c('Biomasa_Crucero', 'CPUE', 'Desembarques') 
sept    <- data.frame(ind_sept) %>% mutate (Asesoría='septiembre_2020') %>% mutate (yrs= yrs)  %>% melt(id.var=c('yrs', 'Asesoría'))

base1 <- data.frame(rbind(ind,junio, sept))  


f1 <- ggplot(base1 %>% filter(Asesoría!='observado', variable=='Biomasa_Crucero'), 
        aes(yrs,value/1000000)) + 
        geom_line(aes(colour=Asesoría), size=1) +
        scale_colour_manual(values=c('black','red')) +
        geom_point(data = base1 %>% filter(Asesoría=='observado', variable=='Biomasa_Crucero'),
        aes(yrs,value/1000000), shape = 19, colour = 'gray30') +
        geom_errorbar(data = base1 %>% filter(Asesoría=='observado', variable=='Biomasa_Crucero'),
        aes(ymin = value*exp(-1.96*cvCB)*10^-6, ymax = value*exp(1.96*cvCB)*10^-6), color = 'gray30') +
        scale_x_continuous(breaks = seq(from = 1985, to = 2020, by = 5)) +
        labs(title='Biomasa de Crucero', x = 'Año', y = 'Toneladas (millones)') +
        theme_bw(base_size=9)


f2 <- ggplot(base1 %>% filter(Asesoría!='observado', variable=='CPUE'), 
            aes(yrs,value/1000000)) + 
        geom_line(aes(colour=Asesoría), size=1) +
        scale_colour_manual(values=c('black','red')) +
        geom_point(data = base1 %>% filter(Asesoría=='observado', variable=='CPUE'),
                   aes(yrs,value/1000000), shape = 19, colour = 'gray30') +
        geom_errorbar(data = base1 %>% filter(Asesoría=='observado', variable=='CPUE'),
                      aes(ymin = value*exp(-1.96*cvcpue)*10^-6, ymax = value*exp(1.96*cvcpue)*10^-6), color = 'gray30') +
        scale_x_continuous(breaks = seq(from = 1985, to = 2020, by = 5)) +
        labs(title='CPUE', x = 'Año', y = 'toneladas/viaje') +
        theme_bw(base_size=9)

f3 <- ggplot(base1 %>% filter(Asesoría!='observado', variable=='Desembarques'), 
            aes(yrs,value/1000)) + geom_line(aes(colour=Asesoría), size=1) +
        scale_colour_manual(values=c('black','red')) +
        geom_point(data = base1 %>% filter(Asesoría=='observado', variable=='Desembarques'),
                   aes(yrs,value/1000), shape = 19, colour = 'gray30') +
        geom_errorbar(data = base1 %>% filter(Asesoría=='observado', variable=='Desembarques'),
                      aes(ymin = value*exp(-1.96*cvdes)*10^-3, ymax = value*exp(1.96*cvdes)*10^-3), color = 'gray30') +
        scale_x_continuous(breaks = seq(from = 1985, to = 2020, by = 5)) +
        labs(title='Desembarques', x = 'Año', y = 'Toneladas (miles)') +
        theme_bw(base_size=9)

f1/f2/f3 + plot_layout(guides="collect")


```


```{r Fig20,warning=F, include=T, message=F, echo=FALSE,eval=TRUE,fig.height=11,fig.width=9,fig.align="center",fig.path="Figuras/",dev=c('pdf')}
# Análisis de Residuales Indices  

# Arreglos MAET - MATT
Res_maet <- data.frame(log(ind_obs) - log(ind_jun)) %>% mutate(yrs = yrs) %>% mutate(Asesoría = 'junio 2021') 
Res_matt <- data.frame(log(ind_obs) - log(ind_sept)) %>% mutate(yrs = yrs) %>% mutate(Asesoría = 'Septiembre 2020')

Res  <- rbind(Res_maet, Res_matt) %>% melt(id.vars= c('yrs','Asesoría'))
pred <- base1 %>% filter(Asesoría!='observado') %>% mutate (pred = log(value)); predm <- pred$pred
Res2 <- cbind(Res,predm)
  

r1<- ggplot(Res, aes(yrs,value)) + 
     geom_bar(aes(fill=Asesoría), stat='identity', position='dodge') +
     scale_fill_manual(values=c("red","black"))+
     geom_hline(yintercept = 0) +
     facet_wrap(. ~ variable,  ncol = 1) + 
     labs(x= 'Año', y = 'Residuales (escala log)') + 
     theme_bw(base_size=12)

r2 <- ggplot(Res2, aes(predm,value)) + 
      geom_point(aes(colour=Asesoría), size = 1.5) +
      scale_colour_manual(values=c('red',"black")) +
      geom_hline(yintercept = 0) +
      facet_wrap(. ~ variable, ncol = 1) +
      labs(x= 'Predicho (log)', y = 'Residuales') +
      theme_bw(base_size=12)

r3 <- ggplot(Res, aes(value, colour=Asesoría)) + 
      geom_histogram(fill='white', position  = 'dodge') +
      facet_wrap(. ~ variable, ncol = 1) + 
      labs(x= 'Residuales', y ='Histograma de Residuos (Frecuencia)') +
      theme_bw(base_size=12)

r4 <-  ggplot(Res, aes(sample = value, colour = Asesoría)) + 
       stat_qq() + 
       stat_qq_line() +
       scale_colour_manual(values=c('red',"black")) +
       facet_wrap(. ~ variable, ncol = 1) + 
       labs(x= 'Sample Quantiles', y ='Theoretical') +
       theme_bw(base_size=12)

 r1+r4 + plot_layout(guides="collect")

```

```{r Fig21,warning=F, include=T, message=F, echo=FALSE,fig.height=6,fig.width=6,fig.asp=1,fig.align="center",fig.path="Figuras/",dev=fig}
age     <-seq(5.5,20,0.5)                                            
nage    <-length(age)    
etf_obs_jun <- data.frame(rep1$Propfl_obs)
etf_pre_jun <- rep1$Propfl_pred

etf_obs_sept <- data.frame(rbind(rep0$Propfl_obs,rep(NA,nage)))
etf_pre_sept <- data.frame(rbind(rep0$Propfl_pred,rep(NA,nage)))

yearf   <- rep1$Years
nyearf  <-length(yearf)  

 obs  <- as.data.frame(etf_obs_jun) %>% mutate(year=yearf) %>% melt(id.vars='year') %>%
              mutate(edad = rep(age, each=nyearf)) %>% mutate(type='obs')
 pred_jun <- as.data.frame(etf_pre_jun) %>% mutate(year=yearf) %>% melt(id.vars='year') %>%
              mutate(edad = rep(age, each=nyearf)) %>% mutate(type='pred_jun')
 
 pred_sept <- as.data.frame(etf_pre_sept) %>% mutate(year=yearf) %>% melt(id.vars='year') %>% mutate(edad = rep(age, each=nyearf)) %>% mutate(type='pred_sept')
  
 mat  <- rbind(obs,pred_jun,pred_sept)
 
 fig1 <- ggplot(filter(mat, type=='obs')) + 
          geom_bar(aes(x = edad, y = value), stat="identity", fill='gray66', color = 'gray28') + 
          facet_wrap(~year, dir = 'v', as.table = TRUE) + labs(x = 'Tallas', y = 'Proporción de tallas de la captura') #, scale='free'
 fig1b <- fig1 + geom_line(data = filter(mat, type=='pred_sept'), aes(x = edad, y = value), color = 'black', size = 1)
 fig1b <- fig1b + geom_line(data = filter(mat, type=='pred_jun'), aes(x = edad, y = value), color = 'red', size = 1)
 
 fig1b + theme(panel.background = element_rect(fill ="gray99")) + theme(panel.grid=element_line(color=NA))
  
```


```{r Fig22,warning=F, include=T, message=F, echo=FALSE,fig.height=7,fig.width=7,fig.asp=1,fig.align="center",fig.path="Figuras/",dev=fig}
age     <-seq(5.5,20,0.5)                                            
nage    <-length(age)    
etc_obs_sept <- data.frame(rbind(rep0$Propcru_obs,rep(NA,nage)))
etc_pre_sept <- data.frame(rbind(rep0$Propcru_pred,rep(NA,nage)))

etc_obs_jun <- data.frame(rep1$Propcru_obs)
etc_pre_jun <- rep1$Propcru_pred

yearc   <- rep1$Years
nyearc  <-length(yearc)  

 obs  <- as.data.frame(etc_obs_jun) %>% mutate(year=yearc) %>% melt(id.vars='year') %>%
              mutate(edad = rep(age, each=nyearc)) %>% mutate(type='obs')
 
 pred_jun <- as.data.frame(etc_pre_jun) %>% mutate(year=yearc) %>% melt(id.vars='year') %>%
              mutate(edad = rep(age, each=nyearf)) %>% mutate(type='pred_jun')
 
 pred_sept <- as.data.frame(etc_pre_sept) %>% mutate(year=yearc) %>% melt(id.vars='year') %>%
              mutate(edad = rep(age, each=nyearf)) %>% mutate(type='pred_sept')
 
 mat  <- rbind(obs,pred_jun,pred_sept)
 
 fig1 <- ggplot(filter(mat, type=='obs')) + 
          geom_bar(aes(x = edad, y = value), stat="identity", fill='gray66', color = 'gray28') + 
          facet_wrap(~year, dir = 'v', as.table = TRUE) + labs(x = 'Tallas', y = 'Proporción de tallas del Crucero') #, scale='free'
 fig1b <- fig1 + geom_line(data = filter(mat, type=='pred_sept'), aes(x = edad, y = value),color = 'black', size = 1)
 fig1b <- fig1b + geom_line(data = filter(mat, type=='pred_jun'), aes(x = edad, y = value),color = 'red', size = 1)
 fig1b + theme(panel.background = element_rect(fill ="gray99")) + theme(panel.grid=element_line(color=NA))
 
```

```{r Fig23, warning=F, include=T, message=F, echo=FALSE,fig.height=7,fig.width=8,fig.align="center",fig.path="Figuras/",dev=fig}
par(mfcol=c(1,2))
#Flota
cx<-0.7
# modelo alternativo
anos        <-rep1$Years
obsF_alt    <-rep1$Propfl_obs
preF_alt    <-rep1$Propfl_pred
resF_alt    <-obsF_alt-preF_alt

rng <-range(resF_alt,na.rm=T)
dd  <-dim(resF_alt)
est <-matrix(NA,nrow=dd[1],ncol=dd[2])

for(j in 1:dd[1]){for(k in 1:dd[2]){val<-resF_alt[j,k]
if(val>0){est[j,k]<-val/rng[2]}
else{est[j,k]<-val/rng[1]*-1}}}

par(mar=c(5.4,6.7,2,1),cex.axis=cx,cex.lab=cx)
image(age,anos,t(est),col=0,yaxt="n",xlab="",ylab="")
ee  <-dim(est)
for(n in 1:ee[1]){for(m in 1:ee[2]){vol<-est[n,m]
if(is.na(vol)==FALSE){
	if(vol>0){points(age[m],anos[n],pch=19,cex=2*sqrt(vol),col=1)}
	if(vol<0){points(age[m],anos[n],pch=1,cex=2*sqrt(vol*-1),col=1)}
}}}

mtext("Flota - junio 2021",side=3,cex=cx)
mtext("Tallas (cm)",side=1,line=3.2,cex=cx);posi<-seq(1,57,by=4)
axis(2,at=anos,labels=anos,las=2,cex=cx)
mtext("Años",side=2,line=4.7,cex=cx)
box()

#Crucero alternativo

obsB_alt <-rep1$Propcru_obs
preB_alt <-rep1$Propcru_pred
resB_alt <-obsB_alt-preB_alt

rng <-range(resB_alt,na.rm=T)
dd  <-dim(resB_alt)
est <-matrix(NA,nrow=dd[1],ncol=dd[2])

for(j in 1:dd[1]){for(k in 1:dd[2]){val<-resB_alt[j,k]
if(val>0){est[j,k]<-val/rng[2]}
else{est[j,k]<-val/rng[1]*-1}}}

par(mar=c(5.4,6.7,2,1),cex.axis=cx,cex.lab=cx)
image(age,anos,t(est),col=0,yaxt="n",xlab="",ylab="")
ee  <-dim(est)
for(n in 1:ee[1]){for(m in 1:ee[2]){vol<-est[n,m]
if(is.na(vol)==FALSE){
	if(vol>0){points(age[m],anos[n],pch=19,cex=2*sqrt(vol),col=1)}
	if(vol<0){points(age[m],anos[n],pch=1,cex=2*sqrt(vol*-1),col=1)}
}}}
mtext("Crucero Acústico - junio 2021",side=3,cex=cx)
mtext("Tallas (cm)",side=1,line=3.2,cex=cx);posi<-seq(1,57,by=4)
axis(2,at=anos,labels=anos,las=2,cex=cx)
mtext("Años",side=2,line=4.7,cex=cx)
box()

```

```{r VariablesJunio_std, echo=F,message=FALSE, warning=FALSE, include=T}

years<-rep1$Years
nyears<-length(years)

Rt1      <- subset(std1,name=="Reclutas")$value 
Rt1std   <- subset(std1,name=="Reclutas")$std
BT1      <- subset(std1,name=="BT")$value   
BT1std   <- subset(std1,name=="BT")$std
BD1      <- subset(std1,name=="BD")$value   
BD1std   <- subset(std1,name=="BD")$std
Ft1      <- subset(std1,name=="log_F")$value   
Ft1std   <- subset(std1,name=="log_F")$std

VarPob_jun<- data.frame(x=years, Rt1=Rt1,BT1=BT1,BD1=BD1,Ft1=exp(Ft1), 
         lowerRt1 = (Rt1 -1.96*Rt1std), upperRt1 = (Rt1+1.96*Rt1std),
         lowerBT1 = (BT1 -1.96*BT1std), upperBT1 = (BT1+1.96*BT1std),
         lowerBD1 = (BD1 -1.96*BD1std), upperBD1 = (BD1+1.96*BD1std),
         lowerFt1 = exp(Ft1 -1.96*Ft1std), upperFt1 = exp(Ft1+1.96*Ft1std))

```


```{r VariablesSeptiembre_std, echo=F,message=FALSE, warning=FALSE, include=T}

years<-rep1$Years
nyears<-length(years)

Rt0      <- c(subset(std0,name=="Reclutas")$value,NA) 
Rt0std   <- c(subset(std0,name=="Reclutas")$std,NA)
BT0      <- c(subset(std0,name=="BT")$value,NA)   
BT0std   <- c(subset(std0,name=="BT")$std,NA)
BD0      <- c(subset(std0,name=="BD")$value,NA)   
BD0std   <- c(subset(std0,name=="BD")$std,NA)
Ft0      <- c(subset(std0,name=="log_F")$value,NA)   
Ft0std   <- c(subset(std0,name=="log_F")$std,NA)

VarPob_sept<- data.frame(x=years, Rt0=Rt0,BT0=BT0,BD0=BD0,Ft0=exp(Ft0), 
         lowerRt0 = (Rt0 -1.96*Rt0std), upperRt0 = (Rt0+1.96*Rt0std),
         lowerBT0 = (BT0 -1.96*BT0std), upperBT0 = (BT0+1.96*BT0std),
         lowerBD0 = (BD0 -1.96*BD0std), upperBD0 = (BD0+1.96*BD0std),
         lowerFt0 = exp(Ft0 -1.96*Ft0std), upperFt0 = exp(Ft0+1.96*Ft0std))

```

```{r Dat_Retrospectivo_junio, eval=F,echo=F, message=FALSE, warning=FALSE, include=T}
dir<-paste(dir.0,"/Retrospectivobase",sep="")
setwd(dir)
admb<-"MTT0920"

years<-rep0$Years
nyears<-length(years)
retros<-seq(1,3)
nretros<-length(retros)
year_retros<-as.factor(years[(nyears-(nretros-1)):nyears])
                      
retroR      <- matrix(0,nrow=nyears,ncol=nretros+1)
retroBD     <- matrix(0,nrow=nyears,ncol=nretros+1)
retroF      <- matrix(0,nrow=nyears,ncol=nretros+1)

for(i in 1:length(retros)){
  rep<- reptoRlist(paste(admb,"s",i,".rep",sep=""))
  retroR[,i+1] <- c(rep$Reclutamiento,rep(NA,i-1))
  retroBD[,i+1] <- c(rep$Biomasa_desovante,rep(NA,i-1))
  retroF[,i+1]  <- c(rep$F,rep(NA,i-1)) }


# retrospectivo relativo (cálculo)
    mohn.r       <- rep(NA, nretros)
    rel.diff.r   <- matrix(NA, nrow=nyears, ncol=(nretros))
    mohn.ssb     <- rep(NA, nretros)
    rel.diff.ssb <- matrix(NA, nrow=nyears, ncol=(nretros))
    mohn.f       <- rep(NA, nretros)
    rel.diff.f   <- matrix(NA, nrow=nyears, ncol=(nretros))

    for(j in 1:nretros){
      rel.diff.r[,j] <- (retroR[,(j+1)]-retroR[,2])/retroR[,2]
      mohn.r[j]      <- rel.diff.r[(nyears-j),j]
      rel.diff.ssb[,j] <- (retroBD[,(j+1)]-retroBD[,2])/retroBD[,2]
      mohn.ssb[j]      <- rel.diff.ssb[(nyears-j),j]
      rel.diff.f[,j]   <- (retroF[,(j+1)]-retroF[,2])/retroF[,2]
      mohn.f[j]        <- rel.diff.f[(nyears-j),j]}
    
    ave.mohn.r    <- mean(mohn.r)
    ave.mohn.ssb  <- mean(mohn.ssb)
    ave.mohn.f    <- mean(mohn.f)
    
 # Arreglo datos

#Para retrospectivo tradicional
Rt_retro<- data.frame(x=years, y1=retroR[,2],y2=retroR[,3],y3=retroR[,4],
                      lower = (Rt1 -1.96*Rt1std), upper = (Rt1+1.96*Rt1std))
BD_retro<- data.frame(x=years, y1=retroBD[,2],y2=retroBD[,3],y3=retroBD[,4],
                      lower = (BD1 -1.96*BD1std), upper = (BD1+1.96*BD1std))
Ft_retro<- data.frame(x=years, y1=retroF[,2],y2=retroF[,3],y3=retroF[,4], 
                      lower = exp(Ft1-1.96*Ft1std), upper = exp(Ft1+1.96*Ft1std))

#Para restrospectivo relativo
Rt_retroRel<- data.frame(x=years, y1=rel.diff.r[,1],y2=rel.diff.r[,2],y3=rel.diff.r[,3])
BD_retroRel<- data.frame(x=years, y1=rel.diff.ssb[,1],y2=rel.diff.ssb[,2],y3=rel.diff.ssb[,3])
Ft_retroRel<- data.frame(x=years, y1=rel.diff.f[,1],y2=rel.diff.f[,2],y3=rel.diff.f[,3])

```



